kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pricelist-db-pvc
  namespace: test-acm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
